### ISSUE TITLE
getMask() Does not work correctly with non-square images.

### ISSUE THREAD

**Issue by georgedeath** [jdoepfert/roipoly.py#1]
Lines 48 and 68 have the references to the dimension sizes the wrong way round, as python returns the y dimension before the x when using np.shape().

![untitled](https://cloud.githubusercontent.com/assets/5173737/8428496/ceea9378-1f16-11e5-86ad-2575f530da15.png)

Changing line 48 to:
ny, nx = np.shape(currentImage)

and line 60 to:
grid = ROIpath.contains_points(points).reshape((ny,nx))

Fixes this issue.

![untitled2](https://cloud.githubusercontent.com/assets/5173737/8428500/dc280ac0-1f16-11e5-95f6-8f606589d7cc.png)

**Comment by jdoepfert** [comment]
thanks for the correction!
