### ISSUE TITLE
Not able to select ROI in Jupyter Notebook

### ISSUE THREAD

**Issue by uddhavbhattarai** [jdoepfert/roipoly.py#22]
I am not able to select polygonal region of interest after `plt.imshow(image)` in Jupyter Notebook. The region within image does not highlight to select the polygon region with `RoiPoly(color='r')`.
Browser: Google Chrome

**Comment by jdoepfert** [comment]
Hi, jupyter notebooks are not (yet) supported. Try running your code in a python script or an interactive python session.

**Comment by jdoepfert** [comment]
You can try using another matplotlib backend though, by putting e.g.` %matplotlib qt ` on the topmost cell of your notebook. See https://stackoverflow.com/questions/14261903/how-can-i-open-the-interactive-matplotlib-window-in-ipython-notebook
