### ISSUE TITLE
IndexError in display_roi

### ISSUE THREAD

**Issue by andersenthomas** [jdoepfert/roipoly.py#25]
Hi,

I'm getting an IndexError when running basic_example.py. After completing my ROI (either by right click or double click) the script terminates abrutly without returning mask or values from the ROI. Traceback from script start below. Any ideas?

`File C:\WinPython-3702\python-3.7.0.amd64\lib\site-packages\roipoly\roipoly.py, line 92, in display_roi`

`line = plt.Line2D(self.x + [self.x[0]], self.y + [self.y[0]],`

`IndexError: list index out of range`

**Comment by jdoepfert** [comment]
duplicates #4, check the comments therein
