### ISSUE TITLE
example not work

### ISSUE THREAD

**Issue by sank96** [jdoepfert/roipoly.py#27]
I cloned the project from git and run it on my Mac.

I try to execute the `basic_example.py` but when the figure is shown it is not able to get my click so no figure is shown. 

<img width="645" alt="image" src="https://user-images.githubusercontent.com/16799929/68885271-1bc7ad80-0715-11ea-916b-9e0eddc00943.png">

**Comment by jdoepfert** [comment]
how exactly did you run the example? are there any logs shown? maybe try installing from pip.

**Comment by migunasekera** [comment]
I am getting a similar issue with this example. I ran this example after cloning the package. When I click I will not see any polygon lines showing up. Right-clicking to close the screen doesn't seem to work either. Only when I close the screen manually, I will receive the following error log:

```
Traceback (most recent call last):
  File "examples/basic_example.py", line 29, in <module>
    roi1.display_roi()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/roipoly/roipoly.py", line 97, in display_roi
    line = plt.Line2D(self.x + [self.x[0]], self.y + [self.y[0]],
IndexError: list index out of range
```

I am using:
- Python version 3.7
- conda version 4.6.14

Please let me know if there is anything else that you would need to figure out the issue.

**Comment by georgedeath** [comment]
> 
> 
> I am getting a similar issue with this example. I ran this example after cloning the package. When I click I will not see any polygon lines showing up. Right-clicking to close the screen doesn't seem to work either. Only when I close the screen manually, I will receive the following error log:
> 
> ```
> Traceback (most recent call last):
>   File "examples/basic_example.py", line 29, in <module>
>     roi1.display_roi()
>   File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/roipoly/roipoly.py", line 97, in display_roi
>     line = plt.Line2D(self.x + [self.x[0]], self.y + [self.y[0]],
> IndexError: list index out of range
> ```
> 
> I am using:
> 
>     * Python version 3.7
> 
>     * conda version 4.6.14
> 
> 
> Please let me know if there is anything else that you would need to figure out the issue.

Are you using spyder? roipoly does not work well (or at all) with spyder.

**Comment by jdoepfert** [comment]
relates to #29
