### ISSUE TITLE
Example work

### ISSUE THREAD

**Issue by Pentaerythritol** [jdoepfert/roipoly.py#28]
Hello, 

I tried to run the basic example in spyder with anaconda. The roi choice works, but once I double click the code "freeze". It seems that if i try to close the kernel, the code is going to the next step and crash.

Thanks for your help !

**Comment by jdoepfert** [comment]
Hi, that's probably due to the Spyder IDE. Please run the script from the terminal.

**Comment by Pentaerythritol** [comment]
Thanks, 

Indeed, i found an issue with Ipython7, but i managed to find a way to make it work within spyder.

Best regards

**Comment by shangharsha2929** [comment]
Hi, @Pentaerythritol how can I run roiPoly within Spyder?

I am using Python 3.7.6 and Ipython 7.12.0 on windows.
I even tried running it on Python 3.9.12 and IPython 8.2.0 but with no success. It runs allows users to draw ROI and after right-clicking, the script freezes and doesn't move to the next step in the script.
Any suggestions are warmly welcomed.
