### ISSUE TITLE
Using an image crash the app

### ISSUE THREAD

**Issue by melkotoury** [jdoepfert/roipoly.py#3]
When using any type of image instead of
`img = pl.ones((100, 100)) * range(0, 100)
`

I used 

```
img = pl.imread("path_to_img")
pl.imshow(img)
```

the first plot is working fine but when I plot the second one , it stop with runtime error

![error](https://cloud.githubusercontent.com/assets/6374780/15809266/67f241b4-2b8d-11e6-8732-857f58e3b3bb.PNG)

**Comment by jdoepfert** [comment]
Hi,

it works only for 2D images, i.e. grayscale images.
You could do

|img = pl.imread("path_to_img")|

img = np.mean(img,2)

to convert your image to grayscale

Am 06/06/16 um 02:22 schrieb Mahmoud El Kotoury:

**Comment by melkotoury** [comment]
Thank you so much , how can i get it to work with PNG and JPEG ??

**Comment by jdoepfert** [comment]
the code you sent should work!

**Comment by shubhamsharma1609** [comment]
when I opened a NumPY array image it shows the image and I am able to draw an ROI but it does not display an ROI ,I am using Python3 and the error is:


[errorroi](https://cloud.githubusercontent.com/assets/11288303/22419224/71a162ea-e702-11e6-8e5f-f9a3b938fd3d.JPG)
