### ISSUE TITLE
Causes Spyder to hang

### ISSUE THREAD

**Issue by MatthewMarzetti** [jdoepfert/roipoly.py#32]
Hello,

I am trying to use this on Spyder v4.1.4 running python v3.7.7. I'm fairly new to python so this might be a simple error on my part.

When I run your example, everything is going fine until I finish drawing my first ROI and right click. This closes the window but the code just hangs. If I interrupt the kernel it continues to hang and I need to restart the kernel. While it is restarting it then shows me the figure with my defined ROI (which looks great and is what I'm looking to achieve), but obviously I can't obtain the mask from that ROI and use it later in my code as I've had to restart everything. Have I configured something wrong to cause this hanging? This happens when I just run the code from your example (https://github.com/jdoepfert/roipoly.py/blob/master/examples/basic_example.py) without changing anything.

Cheers,
Matthew

**Comment by shubham-scisar** [comment]
Yes. Spyder hangs indefinitely after selection of ROI . Please fix this issue.

**Comment by jdoepfert** [comment]
yea, unfortunately, it sometimes does not work with spyder. Can you just start your script from the terminal instead?

**Comment by jdoepfert** [comment]
duplicates #29

**Comment by MatthewMarzetti** [comment]
I can start script from terminal, but something I've found which works for me is to include the line:

matplotlib.use("TkAgg")

At the start of my script (or any point before the first ROI). Changing graphics settings in spyder seems to be a bit more variable but I haven't had any issues using spyder anymore with that line included

**Comment by jdoepfert** [comment]
thanks @MatthewMarzetti for the workaround. I will close this issue then
