### ISSUE TITLE
List index out of range in display roi

### ISSUE THREAD

**Issue by shubham-scisar** [jdoepfert/roipoly.py#4]
when I opened a NumPY array of a grayscale image it shows the image and I am able to draw an ROI but it does not display an ROI ,I am using Python3 and the error is in line 65 of roipoly that list index is out of range, I am attching the snapshot of error:
![errorroi](https://cloud.githubusercontent.com/assets/11288303/22466003/53d0afcc-e7e4-11e6-9fc4-26b47ec6b3e9.JPG)

**Comment by georgedeath** [comment]
Does the example work for you? If so then paste the code that is causing the error.

**Comment by shubham-scisar** [comment]
in the example also same error is coming.
![newerrorroi](https://cloud.githubusercontent.com/assets/11288303/22501055/0755e226-e88d-11e6-9cc5-60957f4e06a9.JPG)

**Comment by georgedeath** [comment]
have you tried running it from the command line instead of through spyder? it may be a conflict in there somehow.

**Comment by jdoepfert** [comment]
for me, the example works from the command line (`python example.py`). I am using python 3.5 with anaconda.

**Comment by shubham-scisar** [comment]
Thanks a lot Joerg!!!!! I am able to make it work from conda console. Kudos to the code!!!!!

**Comment by jdoepfert** [comment]
:+1:

**Comment by MariaLiljeroth** [comment]
I've got this issue as well with the code:

```
`
from roipoly import roipoly
plt.imshow(sample_im2)
MyROI=roipoly(roicolor='r')
mask=MyROI.getmask(sample_im2)`
```

which generates the error:

>   File "C:\Users\FD_Recon_Lung\roipoly.py", line 46, in getMask
    poly_verts = [(self.allxpoints[0], self.allypoints[0])]
IndexError: list index out of range

This works line by line but if you want to run the entire script which includes a call to this function, then move on to using the resulting mask, it isn't ideal. It's like it tries to use properties from MyROI before they are assigned. Is this a generic python issue or specific to this script?

**Comment by jdoepfert** [comment]
Hi @MariaLiljeroth, thx for reporting the error. Can you create a minimal code snippet that reproduces the error without the need of additional files (in your code, `sample_im2` is needed)? Also, which python version are you using and which matplotlib version?

**Comment by MariaLiljeroth** [comment]
Hi, thanks for the quick reply. I am running python 3.6.3 and matplotlib 2.1.0


```
import matplotlib.pyplot as plt
import numpy as np
sample_im=np.random.rand(128,128)
plt.imshow(sample_im)
from roipoly import roipoly
plt.imshow(sample_im)
MyROI=roipoly(roicolor='r')
mask=MyROI.getMask(sample_im)
```

**Comment by jdoepfert** [comment]
@MariaLiljeroth Your example code runs on my computer. I am on a mac, python 3.6.3 and matplotlib 2.2.2.
I updated parts of the code last week, maybe it'll work with the new version..

**Comment by jdoepfert** [comment]
you should be able to install the latest version with pip `pip install git+https://github.com/jdoepfert/roipoly.py`

**Comment by MariaLiljeroth** [comment]
Excellent, thank you. It appears it was the old version of matplotlib that was the culprit.

**Comment by eewvh** [comment]
Hi,
I'm having this same problem using ROIPoly inside a Script in Spyder. It works if I implement the GitHub example you provide line by line, but if I run the example as a script, it fails with the error:

line 84, in display_roi
    line = plt.Line2D(self.x + [self.x[0]], self.y + [self.y[0]],

IndexError: list index out of range

It's exactly as the others have stated above, the code passes on to display_ROI before I've selected the ROI in the image.

Matplotlib 3.0.2
Spyder 3.3.2
Python 3.7.1

**Comment by eewvh** [comment]
Hi, I came up with a VERY UGLY workaround for this problem which may help you resolve it.

In roipoly.py I added a 'completed' Boolean in the class definition:


```
self.ax = ax
self.completed = False

# Mouse event callbacks
```

Then, in the button press callback I added (on a right button click):

```
if sys.flags.interactive:
     pass
else:
     #  Figure has to be closed so that code can continue
      plt.close(self.fig)
self.completed = True
```

Then, to make it work in my script I added (here's the ugly bit):

```
roi1 = RoiPoly(color='r', fig=fig)
while not roi1.completed:
    plt.pause(0.0001)
```

The good news is that it works and I can go on developing my masking script using ROIPOLY. The bad news is that it's ugly and clunky. I'm sure there's a better way!

Thanks still for the very helpful package!

Cheers,
e

**Comment by jdoepfert** [comment]
hi @eewvh, thanks for reporting. Does the `IndexError` also occur when you run the script from the terminal `python script.py` instead of from Spyder?

**Comment by nichojac** [comment]
Hi @jdoepfert, I have the same problem as @eewvh, but I am not using Spyder. I am running example.py as a script in the Terminal and am running into the same error...

Traceback (most recent call last):
  File "example.py", line 31, in <module>
    roi1.display_roi()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/roipoly/roipoly.py", line 92, in display_roi
    line = plt.Line2D(self.x + [self.x[0]], self.y + [self.y[0]],
IndexError: list index out of range

Python 3.7.3
Matplotlib 3.0.3
Pytest 4.4.1
flake8 3.7.7

Any help would be great, thank you!

**Comment by jdoepfert** [comment]
hi @nichojac, how exactly did you run the example, and from which OS?
Try cloning this repository, and then from the terminal run `python examples/basic_example.py`.

**Comment by nichojac** [comment]
I cloned the repository, selected the proper directory containing the examples, and ran the script in terminal. I am using macOS 10.14.3. Same kind of error

`python3 basic_example.py
Traceback (most recent call last):
  File "basic_example.py", line 29, in <module>
    roi1.display_roi()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/roipoly/roipoly.py", line 92, in display_roi
    line = plt.Line2D(self.x + [self.x[0]], self.y + [self.y[0]],
IndexError: list index out of range
`

**Comment by Stecodeven** [comment]
Solution:  
`import matplotlib `
`matplotlib.use('TkAgg')`

Can't believe I stuck in this problem for 3 hours (using roipoly is just the very first step of my project ), even I tried the way that @eewvh mentioned, which is still not working for me. I found for some Mac users, the matplotlib is in non-interactive mode by default, so we just need to set the matplotlib renderer with an interactive backend.
