### ISSUE TITLE
An alternative example for multiple roi regions

### ISSUE THREAD

**Issue by motatoes** [jdoepfert/roipoly.py#7]
Hello!

The example provided in `example.py` demonstrates the use of roipoly.py for a single region of interest. However it would useful to also demo using it for multiple ROIs. I have created a script to demo this. But to get it to work I had to comment out the following lines from the end of `roipoly.py`:

```
if sys.flags.interactive:
    pass
else:
    #figure has to be closed so that code can continue
    print('closing')
    plt.close(self.fig) 
```

And the following script will create two buttons for multiple region selection `unlimited.py:`

```
# import pylab as pl
from matplotlib import pyplot as pl
from matplotlib.widgets import Button
import numpy as np
from roipoly import roipoly 

img = np.ones((100, 100)) * range(0, 100)
ROIs = []
fig = pl.Figure()
done = False

class Callback(object):
  has_next = True
  
  def addROI(self, event):

    # let user draw second ROI
    ROI = roipoly(roicolor='b') #let user draw ROI
    pl.show(block=False)

    # not sure why this is needed to be honest as the figure is
    # already being closed in the ROI class
    pl.close(ROI.fig)

    print('done with rois')
    ROIs.append(ROI)
    print(ROIs)

  def finish(self, event):
    global done
    global ROIs

    # # show ROI masks
    print(ROIs)
    print(len(ROIs))

    done = True
    # close the current figure
    pl.close(pl.gcf())


callback = Callback()

def initUI():
  # show the image
  pl.imshow(img, interpolation='nearest', cmap="Greys")
  pl.colorbar()
  pl.title("left click: line segment         right click: close region")

  pl.subplots_adjust(bottom=0.2)
  ax = pl.gca()
  axprev = pl.axes([0.7, 0.05, 0.1, 0.075])
  axnext = pl.axes([0.81, 0.05, 0.1, 0.075])
  bnext = Button(axnext, 'Add ROI')
  bnext.on_clicked(callback.addROI)
  bprev = Button(axprev, 'Finish')
  bprev.on_clicked(callback.finish)

  [x.displayROI() for x in ROIs]
  [x.displayMean(img) for x in ROIs]

  pl.show()


while not done:
  print(done)
  initUI()


if len(ROIs) >0:
  res = ROIs[0].getMask(img)
  for roi in ROIs:
    res = res + roi.getMask(img)

  pl.imshow(res, interpolation='nearest', cmap="Greys")
  pl.title('mask result')
  pl.show()

```

<img width="659" alt="screen shot 2018-04-11 at 17 26 00" src="https://user-images.githubusercontent.com/1627972/38623299-fe3099ee-3dad-11e8-9f99-a1a2065a8ce9.png">

I'm sharing this to help other users that are using the library. Also happy to submit a PR if it's worthy of merging this example in the library

**Comment by jdoepfert** [comment]
Hi sorry for the late reply. I think further examples could be useful, so I am happy to take a PR! I created an `examples` folder.

**Comment by wukongtea** [comment]
HI,@Mohamed, I used your code ,but it doesn't work, the blue polygon line can't be seen in the picture.Can you tell me why?
![1](https://user-images.githubusercontent.com/25115961/54473351-a7e5a600-4811-11e9-8f0a-bc804c25e86b.png)

**Comment by jdoepfert** [comment]
Plotting multiple rois should now be possible by using the new `MultiRoi` class. Have fun!
