### ISSUE TITLE
How to install roipoly on windows

### ISSUE THREAD

**Issue by niranjanreddy891** [jdoepfert/roipoly.py#8]
I am using python-3.6 with windows-7 64 bit installed. Can anyone please tell me how to install. I used pip to install but no use. :)

**Comment by jdoepfert** [comment]
have you tried going through the readme? pip install numpy and matplotlib, and then try the example.py.

**Comment by jdoepfert** [comment]
should be installable with pip now (`pip install git+https://github.com/jdoepfert/roipoly.py`), see readme. closed by #12
